name: 'Trustworthy Systems CI'
description: |
  Useful common configuration and scripts for the Trustworthy Systems CI.

inputs:
  path:
    description: path to clone this repo relative to GITHUB_WORKSPACE
    default: systems-ci
    required: false

  python:
    description: optional path to python interpreter
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout systems-ci repository
      uses: actions/checkout@v4
      with:
        repository: au-ts/systems-ci
        path: ${{ inputs.path }}

    - name: Install ts_ci
      if: ${{ inputs.python != '' }}
      run: |
        ${{ inputs.python }} -m pip install ${{ inputs.path }}/ts_ci
      shell: bash
